# ~/.bash_aliases
#
# Adriano Freitas - adrianofreitas.me
# 

alias ls='ls --color=auto'
alias steam="LD_PRELOAD='/usr/$LIB/libstdc++.so.6 /usr/$LIB/libgcc_s.so.1 /usr/$

#Scripts
alias shredR='sh /home/afreitas/Scripts/shred-R.sh'
alias firewall='sudo sh /home/afreitas/Scripts/firewall.sh'



